name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (placeholder)
        run: |
          python -c "print('Lint placeholder - no tests run')"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: finnhubmacostrategy
          install_components: 'beta'

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/finnhubmacostrategy/maco/maco:${{ github.sha }} .

      - name: Push Docker image to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker push us-central1-docker.pkg.dev/finnhubmacostrategy/maco/maco:${{ github.sha }}

      - name: Update Cloud Run Job: maco-backfill
        run: |
          gcloud beta run jobs update maco-backfill \
            --image us-central1-docker.pkg.dev/finnhubmacostrategy/maco/maco:${{ github.sha }} \
            --region us-central1

      - name: Update Cloud Run Job: maco-compute-maco
        run: |
          gcloud beta run jobs update maco-compute-maco \
            --image us-central1-docker.pkg.dev/finnhubmacostrategy/maco/maco:${{ github.sha }} \
            --region us-central1

      - name: Update Cloud Run Job: maco-daily-snapshot
        run: |
          gcloud beta run jobs update maco-daily-snapshot \
            --image us-central1-docker.pkg.dev/finnhubmacostrategy/maco/maco:${{ github.sha }} \
            --region us-central1
